### PR TITLE
split cases for different injectors

### LINKED ISSUE #39: Fatal error while component removal
As I was trying to remove `zend-form` from my expressive application with `Composer`, I got the following message:

```
Fatal error: Uncaught Error: Call to undefined method Zend\ComponentInstaller\Injector\ConfigInjectorChain::getConfigFile() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:617
Stack trace:
#0 /app/apps/public/vendor/zendframework/zend-component-installer/src/Collection.php(75): Zend\ComponentInstaller\ComponentInstaller_composer_tmp0->Zend\ComponentInstaller\{closure}(Object(Zend\ComponentInstaller\Injector\ConfigInjectorChain), 1)
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(620): Zend\ComponentInstaller\Collection->each(Object(Closure))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(597): Zend\ComponentInstaller\ComponentInstaller_composer_tmp0->removeModuleFromConfig('Zend\\Form\\Confi...', 'zendframework/z...', Object(Zend\ComponentInstaller\Collection))
#3 /app/apps/public/vendor/zendframework/zend-component-installer/src/Collection.php(75): Zend\ComponentInstaller\ComponentInstal in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 617
```

I guess this is caused by the call to `getConfigFile` present at line `617` of `ComponentInstaller::removeModuleFromConfig`, while that method is not present in `InjectorInterface`

### PR DESCRIPTION
**Pull request by SlayerBirden**
Method `getConfigFile` is not defined in the InjectorInterface hence it's missing from some injectors.
Adjusted logic to apply different "get" logic based on different injector types with default fallback.

This fixes #39

### CODE REVIEW

File: src/ComponentInstaller.php [hunk 1]
```diff
@@ -535,18 +539,44 @@ private function removePackageFromConfig($package, array $metadata, Collection $
...
+                $names[] = $this->getInjectorConfigFileName($item);
+            }
+            $fileName = implode(', ', $names);
+        } elseif ($injector instanceof NoopInjector) {
+            // virtual file name for stub
+            $fileName = 'no-op.conf';
+        } elseif ($injector instanceof AbstractInjector) {
+            // default flow
+            $fileName = $injector->getConfigFile();
+        }
```
Comment (weierophinney) [inline src/ComponentInstaller.php]: Please split each of these cases into its own method, and return the results of calling that method.

As an example:

```php
private function getInjectorConfigFileName(InjectorInterface $injector)
{
    if ($injector instanceof ConfigInjectorChain) {
        return $this->getConfigFileNameFromInjectorChain($injector);
    }
    // etc.
    return '';
}

private function getConfigFileNameFromInjectorChain(ConfigInjectorChain $injector)
{
    $names = [];
    foreach ($injector->getCollection() as $item) {
        $names[] = $this->getInjectorConfigFileName($item);
    }
    return implode(', ', $names);
}
```

**Review by weierophinney — CHANGES_REQUESTED** [review]
A few comments:

- Please add a `@todo` annotation to the `InjectorInterface` to add a `getConfigFile()` method in the next major version.
- Add a `@todo` annotation to `getInjectorConfigFileName()` to remove it for the next major version in favor of the defined `getConfigFile()` method on the interface.
- Please add unit tests so we can validate the fix.

Thanks!

File: src/ComponentInstaller.php (hunk 1 above)
Comment (SlayerBirden) [reply src/ComponentInstaller.php]: @weierophinney done; removed the noop case as it's not actually possible to reach it with current ConfigDiscovery logic

**Comment by SlayerBirden** [comment]
```
okulik@okulik:~/Sites/projects/zend-component-installer$ ./vendor/bin/phpunit --filter testUninstallMessageWithDifferentInjectors
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 203 ms, Memory: 8.00MB

OK (2 tests, 4 assertions)
```
@weierophinney ^ test results

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
Thanks, @SlayerBirden
